Waypoint creation/move/deletion
meshtastic/python pull request #714
Opened 2024-12-18 16:44 UTC by loic-fejoz

Add `MeshInterface.sendWaypoint` to send (create or move) waypoint, and `MeshInterface.deleteWaypoint`  to delete one.
Add an example script to create, move, delete waypoint.

`MeshInterface.sendWaypoint`

Example scripts usage looks like:

``` bash
python3 examples/waypoint.py --port /dev/ttyUSB0 create 45 test "the description" "2024-12-18T23:05:23" 48.74 7.35
python3 examples/waypoint.py delete 45
```

2024-12-18 16:44 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/meshtastic/python?pullRequest=714) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/meshtastic/python?pullRequest=714) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/meshtastic/python?pullRequest=714) it.</sub>

2024-12-21 05:48 UTC, ianmcorvidae requested changes
Thanks for the pull request! I've got a few questions and some things that appear to be missing. Would love to see this added to the API!

2024-12-21 05:48 UTC, ianmcorvidae commented on meshtastic/mesh_interface.py
> +            onResponse = self.onResponseWaypoint
This function doesn't appear to exist.

2024-12-21 05:48 UTC, ianmcorvidae commented on meshtastic/mesh_interface.py
> +            self.waitForWaypoint()
This doesn't seem to exist either.

2024-12-21 05:48 UTC, ianmcorvidae commented on meshtastic/mesh_interface.py
> +            w.id = math.floor(seed * math.pow(2, -32) * 1e9)
What is the source of this ID generation formula? Looking at the other clients, android seems to just use whatever would be the next packet ID and apple seems to generate a random one.

2024-12-21 09:40 UTC, loic-fejoz commented on meshtastic/mesh_interface.py
> +            onResponse = self.onResponseWaypoint
My bad, I forgot those indeed.
Latest commit add them but I am not sure how they should really behave from a protocol perspective. So please guide me if it is wrong.

2024-12-21 09:41 UTC, loic-fejoz commented on meshtastic/mesh_interface.py
> +            self.waitForWaypoint()
see commit 7cc18e9df627a8730fdd1777789230c239bf5e0a

2024-12-21 09:43 UTC, loic-fejoz commented on meshtastic/mesh_interface.py
> +            w.id = math.floor(seed * math.pow(2, -32) * 1e9)
I have done similar has in [javascript API](https://github.com/meshtastic/js/blob/715e35d2374276a43ffa93c628e3710875d43907/src/meshDevice.ts#L791).
Note that it is not a packet ID but a waypoint ID.

2024-12-27 16:33 UTC, ianmcorvidae commented on meshtastic/mesh_interface.py
> +            w.id = math.floor(seed * math.pow(2, -32) * 1e9)
Fair enough. I'm not sure why restricting it to 9 digits is useful, but it's probably fine in any case for this applicaiton.

2024-12-27 16:34 UTC, ianmcorvidae commented on meshtastic/mesh_interface.py
> +            onResponse = self.onResponseWaypoint
These functions are what'd normally be used by the CLI if it supported this stuff, but of course this PR doesn't include that. For now, I think they can just serve as placeholders, so what you have should be fine, I think.

2024-12-27 16:34 UTC, ianmcorvidae approved these changes

2024-12-27 16:34 UTC, ianmcorvidae commented
I'm just running the CI checks on this to see if anything pops up there. As long as that's all fine, this seems good to merge.

2024-12-27 16:46 UTC, merged